version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.htmlss:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ross
    restart: always
