AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceName:
    Type: String
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0c7217cdde317cfec  # Replace with a valid AMI ID
      InstanceType: t2.micro  # Replace with the desired instance type
      KeyName: devops_lab_key_pair   # Replace with your key pair name
      VpcId: vpc-00efe46cf7dbd691e
      Tags:
        - Key: Name
          Value: !Ref InstanceName
